Version updates (since DR2) and resulting build fixes
jboss-developer/jboss-jdg-quickstarts pull request #173
Opened 2017-09-18 11:08 UTC by jsenko

I've updated two dependency versions, and the spark one (result of an update of spark in jdg-spark)
caused a compilation failure fix I fixed quickly so I could proceed with the release.

Please check if the fixes are correct and complete.

2017-11-08 14:27 UTC, ghost requested changes

2017-11-08 14:27 UTC, gustavonalle commented on spark/pom.xml
> +        <version.spark>2.1.0</version.spark>
We should target Spark 2.2.0

2017-11-08 14:27 UTC, gustavonalle commented on spark/pom.xml
>          <version.spark.connector>7.2.0-redhat-SNAPSHOT</version.spark.connector>
This version is wrong, it should be ```0.5.0-redhat-SNAPSHOT```

2017-11-08 14:27 UTC, gustavonalle commented on spark/spark-temperature-analysis/src/main/scala/org/infinispan/quickstart/spark/TemperatureAnalysis.scala
> +      val ispnStream = new InfinispanInputDStream[String, Double](ssc, StorageLevel.MEMORY_ONLY, org.infinispan.spark.config.ConnectorConfiguration(configIn.asInstanceOf[java.util.Map[String, String]
The configuration via ```Properties``` has been [replaced](http://blog.infinispan.org/2017/04/infinispan-spark-connector-05-released.html).
So this snippet is better written as:
```scala
import org.infinispan.spark.config.ConnectorConfiguration;
...
val configIn = new ConnectorConfiguration().setCacheName("inputDataGridCache").setServerList(dataGridServer)
val ispnStream = new InfinispanInputDStream[String, Double](ssc, StorageLevel.MEMORY_ONLY, configIn) 
```

2017-11-08 14:27 UTC, gustavonalle commented on spark/spark-temperature-analysis/src/main/scala/org/infinispan/quickstart/spark/TemperatureAnalysis.scala
> +      avgTemperatures.writeToInfinispan(org.infinispan.spark.config.ConnectorConfiguration(configOut.asInstanceOf[java.util.Map[String, String]].asScala.toMap))
The same applies to this change: create a ```ConnectorConfiguration``` and pass it directly to the ```writeToInfinispan``` method.

2017-11-28 19:02 UTC, closed without merging

2017-11-28 19:03 UTC, jsenko commented
See https://github.com/jboss-developer/jboss-jdg-quickstarts/pull/180