Versions
jboss-developer/jboss-jdg-quickstarts pull request #211
Opened 2018-09-19 15:54 UTC by karesti

2018-09-20 09:22 UTC, galderz requested changes

2018-09-20 09:22 UTC, galderz commented on caching-service/pom.xml
> +    <parent>
Why is this needed?

Even if it's needed, it should be pointing to the JDG version of the parent.

2018-09-20 10:05 UTC, karesti commented on caching-service/pom.xml
> +    <parent>
I added the parent as I was told in a private conversation, and at first nothing was building and the pom parent of the quickstarts is not the parent of any of them. 
I've removed everything, and indeed, it seems not necessary so I'm removing them all. The bom's parent is the infinispan-build-configuration-parent in datagrid.

2018-09-20 10:22 UTC, karesti commented on caching-service/pom.xml
> +    <parent>
well, if i don't put it in the hadoop example, it fails. Now I'm thinking that I have all the dependencies locally, so I'm rebuilding the examples from an empty maven repository.

2018-09-20 13:09 UTC, karesti commented on caching-service/pom.xml
> +    <parent>
@galderz updated

2018-09-21 14:03 UTC, karesti commented
@galderz is it fine for you now Galder ?

2018-09-24 14:20 UTC, galderz commented
Looks good. Is there a CI run for this?

2018-09-24 15:12 UTC, galderz commented
@karesti Running locally I see:

```
[ERROR] The build could not read 4 projects -> [Help 1]
[ERROR]
[ERROR]   The project org.jboss.quickstarts.jdg:jboss-spring-jdg:7.3.0-SNAPSHOT (/Users/g/1/jboss-jdg-quickstarts/spring/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.jboss.spec.javax.transaction:jboss-transaction-api_1.1_spec:jar is missing. @ line 70, column 21
[ERROR]
[ERROR]   The project org.jboss.quickstarts.jdg:jboss-spring-boot-session-tomcat:7.3.0-SNAPSHOT (/Users/g/1/jboss-jdg-quickstarts/spring-session/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.jboss.spec.javax.transaction:jboss-transaction-api_1.1_spec:jar is missing. @ line 65, column 21
[ERROR]
[ERROR]   The project org.jboss.quickstarts.jdg:jboss-carmart-tx:7.3.0-SNAPSHOT (/Users/g/1/jboss-jdg-quickstarts/carmart-tx/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.jboss.spec.javax.transaction:jboss-transaction-api_1.1_spec:jar is missing. @ line 180, column 21
[ERROR]
[ERROR]   The project org.jboss.quickstarts.jdg:jboss-hadoop-quickstart:7.3.0-SNAPSHOT (/Users/g/1/jboss-jdg-quickstarts/hadoop/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.apache.flink:flink-java:jar is missing. @ line 80, column 21
```

With this from root:

```bash
mvn -DskipTests=true clean install -s settings.xml
```

2018-10-01 10:31 UTC, galderz commented
@karesti Is this fixed?

2018-10-01 14:58 UTC, karesti commented
@galderz still need to do by hand the mvn clean install for ``` jdg/build-configuration```

2018-10-23 12:52 UTC, galderz commented
@karesti Merging this for now, please sort out CI as soon as possible.

2018-10-23 12:52 UTC, merged